### ISSUE TITLE
pnpm build: "Type error: Expected 0 arguments, but got 1. "

### ISSUE THREAD

**Issue by ofranquesa** [QuiiBz/next-international#198] opened 2023-09-27 20:35 UTC
**Describe the bug**
When trying to build the next.js app (pnpm build command), the process throws this error with exit status = 1.

**To Reproduce**
1. go to console
2. run "pnpm build"
3. wait for compilation
4. build fails due to the "type error"

**Expected behavior**
After checking the type declaration on your plugin, this error shouldn't happen since clearly the function allows arguments.

**Screenshots**
<img width="1085" alt="Captura de Pantalla 2023-09-27 a las 22 33 14" src="https://github.com/QuiiBz/next-international/assets/77303119/8698c8d2-e87d-48bf-a178-8b478d68291a">

**About (please complete the following information):**
 - next-international version 1.0.1
 - Next.js version 13.4

**Comment by QuiiBz** [comment] 2023-09-28 05:57
Could you send your complete `middleware.ts` file or a reproduction link? I'm not able to reproduce the error in any project using next-international nor in the example: https://github.com/QuiiBz/next-international/tree/main/examples/next-app

**Comment by ofranquesa** [comment] 2023-09-28 07:56
Thanks for your prompt reply!

By the end, I've end up changing the format from .ts -> .js and it worked out. Obviously I had to remove some little TS notation.

I've basically copied your middleware.ts from the documentation:

`// middleware.ts
import { createI18nMiddleware } from 'next-international/middleware'
import { NextRequest } from 'next/server'
 
const I18nMiddleware = createI18nMiddleware({
  locales: ['en', 'de'],
  defaultLocale: 'de'
})
 
export function middleware(request: NextRequest) {
  return I18nMiddleware(request)
}
 
export const config = {
  matcher: ['/((?!api|static|.*\\..*|_next|favicon.ico|robots.txt).*)']
}`

**Comment by QuiiBz** [comment] 2023-09-28 11:29
This seems to be an issue with your TypeScript config, as we have the same `middleware.ts` file in this example and it's working fine: https://codesandbox.io/p/sandbox/jovial-paper-skkprk?file=%2Fmiddleware.ts

I'll close the issue but feel free to send a reproduction that can showcase the same error!

**Closed by QuiiBz** 2023-09-28 11:29 UTC
Labels: needs reproduction

**Comment by walterspieler** [comment] 2023-12-21 19:06
Hello here! 
Hope you're doing well!

I have the same error and switching the middlware file to js worked for me as well (thank you!) but it doesnt feel like the right way to do so .


For info here's my tsconfig

```
{
  "compilerOptions": {
    "removeComments": true,
    "preserveConstEnums": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowUnreachableCode": false,
    "noFallthroughCasesInSwitch": true,
    "outDir": "out",
    "declaration": true,
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": {
      "@/*": ["./src/*"],
      "@/public/*": ["./public/*"]
    },
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "exclude": ["./out/**/*", "./node_modules/**/*"],
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    "app/middleware.js"
  ]
}
```

Thank you, Matt.

**Comment by walterspieler** [comment] 2023-12-21 19:45
Ok, I could make the build work using the same next config you use. But it still doesnt feel right to ignorebuilderrors and ignoreDuringBuilds: 
```
 /** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ['next-international', 'international-types'],
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  // Uncomment to set base path
  // basePath: '/base',
  // Uncomment to use Static Export
  // output: 'export',
};

module.exports = nextConfig;
```

**Comment by QuiiBz** [comment] 2023-12-23 07:55
> Ok, I could make the build work using the same next config you use. But it still doesnt feel right to ignorebuilderrors and ignoreDuringBuilds:

We don't recommend at all to use `eslint.ignoreDuringBuilds` / `typescript.ignoreBuildErrors`, that depends on your project setup (in our case, we already run eslint & typescript in all the monorepo at once, so it's not needed to run it there too)
