### ISSUE TITLE
Localization is not saved when clicking on a link

### ISSUE THREAD

**Issue by stug111** [QuiiBz/next-international#138] opened 2023-08-25 14:24 UTC
When changing the language and following the link, the previous locale is displayed. The problem can be observed at the link https://codesandbox.io/p/sandbox/jovial-paper-skkprk?file=%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A1%2C1.

How to reproduce:
1) Follow the link
2) Change language
3) Click another link

**Comment by QuiiBz** [comment] 2023-08-25 15:32
Interesting bug, I'll take a look this weekend. Refreshing after changing the locale and navigating properly uses the new locale though, so it must be an issue on the frontend.

**Comment by stug111** [comment] 2023-08-28 06:56
@QuiiBz Did you get the problem solved?

**Comment by QuiiBz** [comment] 2023-08-28 06:58
Not yet, it's harder than it seems.

**Comment by stug111** [comment] 2023-08-28 13:36
I also noticed another bug, which is apparently related to the current bug.  When clicking on links, sometimes this error pops up.

![Снимок экрана 2023-08-28 в 15 28 53](https://github.com/QuiiBz/next-international/assets/27495069/a721d526-1725-459c-84c2-8d71e34dd108)

As I understand, it is just related to url segments. One such place is right here https://github.com/QuiiBz/next-international/blob/main/packages/next-international/src/app/client/create-use-current-locale.ts#L8-L9. When debugging, I found that when I click on the link, for some reason the previous locale is retrieved, not the one in the url

**Comment by stug111** [comment] 2023-08-29 12:23
This seems to be a problem with the way nextjs works. If you use references like
```tsx
<Link href="/products">...</Link>
```
then apparently nextjs starts caching these requests and gives the result with the previous locale. This can be tracked in the request middleware.

As a workaround, I put the locale in the links.
```tsx
<Link href={/${locale}/products}>...</Link>
```

**Comment by QuiiBz** [comment] 2023-08-29 15:51
Good finding, I'm not sure if this is the intended behavior of Next.js or a bug.

**Comment by gustaveWPM** [comment] 2023-08-29 16:03
Well, I notice that the value of the `"Next-Locale"` cookie is not always synchronized with the language currently being browsed by the user. However, at the moment, I am unaware of whether there is a connection between these "out-of-sync" situations and those expressed in the issue...

**Comment by QuiiBz** [comment] 2023-08-30 05:58
More investigation:

Refreshing and changing the locale without navigating first works fine: subsequent navigations use the correct locale. If you navigate to some pages, then change the locale, then navigate to **new pages**, the locale is also correct - but not if you navigate to pages you've already visited before (in the same session).

This indeed looks like a caching issue of the paths segment -> RSC payload that are out of sync when a path segment is updated.

**Comment by QuiiBz** [comment] 2023-08-30 06:24
> On subsequent navigations or during prefetching, Next.js will check if the React Server Components Payload is stored in Router Cache. If so, it will skip sending a new request to the server.
If the route segments are not in the cache, Next.js will fetch the React Server Components Payload from the server, and populate the Router Cache on the client.

Next.js docs that mention exactly what I'm talking about above: https://nextjs.org/docs/app/building-your-application/caching#5-subsequent-navigations

**Comment by QuiiBz** [comment] 2023-08-30 06:35
I've published [0.9.4](https://github.com/QuiiBz/next-international/releases/tag/0.9.4) which should fix the issue (see #140), could you confirm that it's the case?

**Comment by stug111** [comment] 2023-08-30 07:03
Thanks. Tested the new version quickly, everything seems to be fine. During the day I'll look at the overall work, if I don't catch any errors, I think can close it issue.

**Comment by QuiiBz** [comment] 2023-08-31 06:35
Closing as it should be resolved, feel free to open a new issue if it's not the case.

**Closed by QuiiBz** 2023-08-31 06:35 UTC
Labels: bug
