### ISSUE TITLE
Client Components mismatching translations during static rendering

### ISSUE THREAD

**Issue by landvibe** [QuiiBz/next-international#190] opened 2023-09-21 23:23 UTC
After executing next build, if I open the `.next/server/app/en.html` file, I can see that the keys inputted into the t function of useI18n are exposed.
In other words, the translated values are not displayed.
The t function of getI18n works properly.
Is this a known issue?

**Comment by QuiiBz** [comment] 2023-09-22 06:17
Could you share a minimal reproduction? This seems like a bug that I haven't experienced before.

**Comment by gustaveWPM** [comment] 2023-09-23 05:48
Lol, I have the same issue.
![Oops](https://github.com/QuiiBz/next-international/assets/118654172/43682d97-ced7-46fc-ae6c-bb30beec7786)

**Comment by QuiiBz** [comment] 2023-09-23 14:08
Closing in favor of #191 which provides a reproduction.

**Comment by gustaveWPM** [comment] 2023-09-23 23:14
> Closing in favor of #191 which provides a reproduction.

ping @QuiiBz 
Oh, srsly?
Idk if the snippets really help to reproduce the bug. Does it?
I just sent some lines of my code.

**Comment by gustaveWPM** [comment] 2023-09-23 23:16
I think this issue also points to another problem, because "Fallbacking on the default language" as I mentioned in my issue (https://github.com/QuiiBz/next-international/issues/191) would already be a good step forward, but this issue also takes into account the problem of having to _statically generate the various contents **with the right language**_.

**Comment by QuiiBz** [comment] 2023-09-25 16:39
*I think* that's because you have a `'use client'` in your root layout, so your pages are also client and thus when pre-rendered, uses the `fallbackLocale`.

I'm wondering how Next.js behaves if we trigger a loading state to force the correct locale to load completely before pre-rendering a page. I'll dig later.

**Comment by gustaveWPM** [comment] 2023-09-25 16:41
> _I think_ that's because you have a `'use client'` in your root layout, so your pages are also client and thus when pre-rendered, uses the `fallbackLocale`.
> 
> I'm wondering how Next.js behaves if we trigger a loading state to force the correct locale to load completely before pre-rendering a page. I'll dig later.

_I think_ you're right about my _root layout_, haha.
```tsx
'use client';

import '@/app/globals.css';
import NextTopLoader from '@/components/misc/NextTopLoader';
import SplashScreen from '@/components/misc/SplashScreen';
import SitewideNavbar from '@/components/navbar/SitewideNavbar';
import { fallbackLocale } from '@/config/i18n';
import { ProgressbarConfig } from '@/config/progressbar';
import SessionProvider from '@/contexts/SessionProvider';
import { I18nProviderClient, useCurrentLocale } from '@/i18n/client';
import { LayoutMinimalProps } from '@/types/CustomUtilitaryTypes';

export default function RootLayout({ children }: LayoutMinimalProps) {
  return (
    <I18nProviderClient fallbackLocale={fallbackLocale}>
      <html lang={useCurrentLocale()}>
        <body className="flex flex-col h-screen w-full p-0 m-0">
          <SplashScreen />
          <NextTopLoader {...{ ...ProgressbarConfig.PROPS }} />
          <SessionProvider>
            <SitewideNavbar />
            {children}
          </SessionProvider>
        </body>
      </html>
    </I18nProviderClient>
  );
}
```

**Comment by gustaveWPM** [comment] 2023-09-25 16:55
Well, I tried to workaround it like this:

```tsx
// RootLayoutClient.tsx

'use client';

import NextTopLoader from '@/components/misc/NextTopLoader';
import SplashScreen from '@/components/misc/SplashScreen';
import SitewideNavbar from '@/components/navbar/SitewideNavbar';
import { fallbackLocale } from '@/config/i18n';
import PROGRESSBAR_CONFIG from '@/config/progressbar';
import SessionProvider from '@/contexts/SessionProvider';
import { I18nProviderClient, useCurrentLocale } from '@/i18n/client';
import { LayoutMinimalProps } from '@/types/CustomUtilitaryTypes';
import { FunctionComponent } from 'react';

interface RootLayoutClientProps extends LayoutMinimalProps {}

const RootLayoutClient: FunctionComponent<RootLayoutClientProps> = ({ children }) => {
  return (
    <I18nProviderClient fallbackLocale={fallbackLocale}>
      <html lang={useCurrentLocale()}>
        <body className="flex flex-col h-screen w-full p-0 m-0">
          <SplashScreen />
          <NextTopLoader {...{ ...PROGRESSBAR_CONFIG.PROPS }} />
          <SessionProvider>
            <SitewideNavbar />
            {children}
          </SessionProvider>
        </body>
      </html>
    </I18nProviderClient>
  );
};

export default RootLayoutClient;
```

```tsx
// src/app/[locale]/layout.tsx

import '@/app/globals.css';
import RootLayoutClient from '@/components/_workarounds/RootLayoutClient';
import { LayoutMinimalProps } from '@/types/CustomUtilitaryTypes';

export default function RootLayout({ children }: LayoutMinimalProps) {
  return <RootLayoutClient {...{ children }} />;
}
```

But it changed absolutely nothing. :<

**Comment by QuiiBz** [comment] 2023-09-27 06:33
I've looked a bit and the issue occurs when using a client component while pre-rendering a page. Because locales are lazy-loaded on the client, the `fallbackLocale` is used in all pages.

An easy fix would be to set the correct `fallbackLocale` based on the current locale params:

```tsx
<I18nProviderClient fallbackLocale={params.locale === 'en' ? en : fr}>
  {children}
</I18nProviderClient>
```

**Comment by gustaveWPM** [comment] 2023-09-27 07:15
Great!
I’ll try it ASAP.

Maybe fallbackLocale could be initialized "For free" in a next release?

**Comment by gustaveWPM** [comment] 2023-09-27 09:57
Hmmm...

```ts
const I18nProvider: FunctionComponent<I18nProviderProps> = ({ children }) => (
  <I18nProviderClient fallbackLocale={LANGS[useCurrentLocale()]}>{children}</I18nProviderClient>
);
```

```ts
import de from '@/i18n/locales/de';
import en from '@/i18n/locales/en';
import fr from '@/i18n/locales/fr';

export const LANGS: Record<LanguageFlag, VocabType> = {
  fr,
  en,
  de
};
```

It fixed the issue.
I'm not a big fan of having to manually import all the languages files, do you think you'll be able to do something a bit more "For free" in a future version? Maybe thank to the _locales_ object passed to `createI18nClient()` ?

**Comment by QuiiBz** [comment] 2023-09-27 10:22
The issue with this approach is that all locales are now loaded client-side, and that's not something we want. We have to find a way to trigger to dynamically load the requested locale and wait until it's complete to continue pre-rendering (the current behavior doesn't wait and pre-renders immediately, causing it to show the keys OR the fallback locale).

**Comment by gustaveWPM** [comment] 2023-09-27 15:39
> The issue with this approach is that all locales are now loaded client-side, and that's not something we want. We have to find a way to trigger to dynamically load the requested locale and wait until it's complete to continue pre-rendering (the current behavior doesn't wait and pre-renders immediately, causing it to show the keys OR the fallback locale).

Would it be possible to get rid off `fallbackLocale` in the `I18nProviderClient` and just load it via the `useCurrentLocale()` hook, based on the _locales_ object provided in `createI18nClient()`?

Something like:
```ts
export const { useI18n: getClientSideI18n, useScopedI18n, I18nProviderClient, useCurrentLocale } = createI18nClient({
  fr: () => import('@/i18n/locales/fr'),
  en: () => import('@/i18n/locales/en'),
  de: () => import('@/i18n/locales/de')
});
```
```ts
const currentLocale = useCurrentLocale() => 'fr' | 'en' | 'de'
loadLocale(currentLocale) => {
  fr: () => import('@/i18n/locales/fr'),
  en: () => import('@/i18n/locales/en'),
  de: () => import('@/i18n/locales/de')
}[currentLocale]
```

Idk if it is achievable?

**Comment by QuiiBz** [comment] 2023-09-27 15:41
That's the goal yes, but this doesn't solve our issue:

> We have to find a way to trigger to dynamically load the requested locale and wait until it's complete to continue pre-rendering

**Comment by gustaveWPM** [comment] 2023-09-27 15:42
> That's the goal yes, but this doesn't solve our issue:
> 
> > We have to find a way to trigger to dynamically load the requested locale and wait until it's complete to continue pre-rendering

Yep. :/
Idk. Sorry.

**Comment by gustaveWPM** [comment] 2023-09-27 15:43
Maybe a _server action_?

**Comment by QuiiBz** [comment] 2023-09-28 06:32
I got something working with [React's `use()` hook](https://react.dev/reference/react/use) and will make a PR this weekend to hopefully fix the issue, and remove the need for `fallbackLocale`

**Comment by gustaveWPM** [comment] 2023-09-28 13:23
> I got something working with [React's `use()` hook](https://react.dev/reference/react/use) and will make a PR this weekend to hopefully fix the issue, and remove the need for `fallbackLocale`

GG!
Very curious to see this PR.

**Comment by QuiiBz** [comment] 2023-09-29 15:26
@gustaveWPM could you try installing `next-international@rc` and removing both `fallback` and `fallbackLocale` props from `I18nProviderClient`?

**Comment by DennieMello** [comment] 2023-09-29 16:01
> @gustaveWPM could you try installing `next-international@rc` and removing both `fallback` and `fallbackLocale` props from `I18nProviderClient`?

When you press the back button in the browser, an error occurs - "Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server."

**Comment by QuiiBz** [comment] 2023-09-29 16:16
Sorry, I forgot to mention that you also have to wrap `I18nClientProvider` with a `Suspense` boundary:

```tsx
<Suspense fallback={<p>Loading...</p>}>
  <I18nProviderClient>{children}</I18nProviderClient>
</Suspense>
```

**Comment by gustaveWPM** [comment] 2023-09-29 16:57
> @gustaveWPM could you try installing `next-international@rc` and removing both `fallback` and `fallbackLocale` props from `I18nProviderClient`?

Yeh. Gonna try it rn.

**Comment by gustaveWPM** [comment] 2023-09-29 17:05
> Sorry, I forgot to mention that you also have to wrap `I18nClientProvider` with a `Suspense` boundary:
> 
> ```tsx
> <Suspense fallback={<p>Loading...</p>}>
>   <I18nProviderClient>{children}</I18nProviderClient>
> </Suspense>
> ```

Hmm.
The SSG seems to be fixed on my project too.

But I have some flickering when I start the website for the first time.

```tsx
  <Suspense>
    <I18nProviderClient>{children}</I18nProviderClient>
  </Suspense>
```

I guess that `children` is re-rendered?

**Comment by QuiiBz** [comment] 2023-09-30 06:03
`I18nProviderClient` should be around the `children` directly, instead of wrapping even the `html`, `body`... tags. Instead of using `useCurrentLocale()` for the `lang` prop, you can use the `params` prop from Next.js to retrieve the `locale` segment:

```tsx
const HtmlElement = ({ children, params }: { children: ReactElement, params: { locale: string } }) => (
  <html lang={params.locale}>
    <body className="flex flex-col min-h-screen w-full p-0 m-0">
      <NextTopLoader {...{ ...PROGRESSBAR_CONFIG }} />
      <SessionProvider>
        <SitewideNavbar />
        <I18nProvider>
          {children}
        </I18nProvider>
      </SessionProvider>
    </body>
  </html>
);
```

**Comment by gustaveWPM** [comment] 2023-10-01 07:59
> `I18nProviderClient` should be around the `children` directly, instead of wrapping even the `html`, `body`... tags. Instead of using `useCurrentLocale()` for the `lang` prop, you can use the `params` prop from Next.js to retrieve the `locale` segment:
> 
> ```tsx
> const HtmlElement = ({ children, params }: { children: ReactElement, params: { locale: string } }) => (
>   <html lang={params.locale}>
>     <body className="flex flex-col min-h-screen w-full p-0 m-0">
>       <NextTopLoader {...{ ...PROGRESSBAR_CONFIG }} />
>       <SessionProvider>
>         <SitewideNavbar />
>         <I18nProvider>
>           {children}
>         </I18nProvider>
>       </SessionProvider>
>     </body>
>   </html>
> );
> ```

Thx!
It looks fine now.

**Comment by QuiiBz** [comment] 2023-10-01 08:03
Great, thanks for testing! I'll complete the PR and release it as part of the 1.1.0 release.

**Comment by QuiiBz** [comment] 2023-10-01 08:42
I've published `next-international@1.1.0-rc.1`: to upgrade from `next-international@1.0.1`, simply remove the `fallbackLocale` prop from `I18nProviderClient`. You no longer need to manually add a `Suspense` boundary, as it is now done by next-international.

Static Rendering should now work as expected when having Client Components in a page (and should still work with fully Client Component pages)

**Closed by QuiiBz** 2023-10-01 08:42 UTC
Labels: bug

**Comment by gustaveWPM** [comment] 2023-10-01 10:00
Hmmm, @QuiiBz, have you any error like this in your browser console?

> Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

**Comment by QuiiBz** [comment] 2023-10-01 10:14
Can you share the PR/commit that have this error? I don't have it on the example app.

**Comment by gustaveWPM** [comment] 2023-10-01 10:19
> Can you share the PR/commit that have this error? I don't have it on the example app.

I'm refactoring a lot of things in my project, I'm not sure that it comes from the current RC.
