### ISSUE TITLE
question: if i have alot of translations for alot of pages, how to load only the nessisary translation ?

### ISSUE THREAD

**Issue by zakidze** [QuiiBz/next-international#304] opened 2023-12-15 10:26 UTC
say i have home page about page ....

how to load home page only home page translations 
about page only about page translations ,

home.json
about.json
contact.json 

how in landing page load only home.json and not about.json

**Comment by QuiiBz** [comment] 2023-12-20 11:07
Duplicate of https://github.com/QuiiBz/next-international/issues/267, this feature isn't supported yet.

**Closed by QuiiBz** 2023-12-20 11:07 UTC
Labels: bug
