### ISSUE TITLE
Bug: nested object locales only returning keys

### ISSUE THREAD

**Issue by bastibuck** [QuiiBz/next-international#67] opened 2023-07-18 12:04 UTC
Hi, 

we just included this lib in our new codebase and it works like a charm when using the dot-notation. Since the docs stated we can also use nested objects and we'd prefer this syntax we tried it with the provided examples from the docs but it doesn't work. 

Can you confirm? Or are we doing something wrong?

The types are working properly after your latest version #66

**Comment by QuiiBz** [comment] 2023-07-18 17:05
Hi, are you using the latest version of next-international? #66 was released in [version 0.6.1](https://github.com/QuiiBz/next-international/releases/tag/0.6.1). If yes, could you provide a minimal reproduction? I'm not able to reproduce on my side.

**Comment by bastibuck** [comment] 2023-07-19 06:02
Thanks for the quick response. 

Yes I was using the latest version. See this https://codesandbox.io/p/sandbox/stoic-greider-m5dvq7 

- uses latest version 0.6.1
- includes client and server translations
- `locales/en.ts` includes both the working and non-working version

**Closed** 2023-07-19 16:12 UTC
Labels: bug

**Comment by QuiiBz** [comment] 2023-07-19 16:15
Thanks, I was able to reproduce and fix the issue in #69. The new version [0.6.2](https://github.com/QuiiBz/next-international/releases/tag/0.6.2) should be working as expected.

**Comment by bastibuck** [comment] 2023-07-20 05:42
Thank you for the quick fix :) It works great now

**Comment by marcohaferkamp** [comment] 2023-07-20 13:45
Thanks for the fix! 
For server components it works great, but sadly it does not seem to work properly in client components.

**Comment by QuiiBz** [comment] 2023-07-20 14:10
I'm not able to reproduce the issue on Client Components using the codesandbox provided above ([codesandbox.io/p/sandbox/stoic-greider-m5dvq7](https://codesandbox.io/p/sandbox/stoic-greider-m5dvq7))


<img width="1327" alt="Screenshot 2023-07-20 at 16 08 52" src="https://github.com/QuiiBz/next-international/assets/43268759/2e9eb18f-8b22-4319-8855-9ef56dbdd454">

Could you share a reproduction link?

**Comment by marcohaferkamp** [comment] 2023-07-20 14:34
Yes sorry, I forgot to mention that we also added some fallback locales to prevent the app from showing translation keys.
I added it to the codesandbox example: https://codesandbox.io/p/sandbox/modest-herschel-tz2dj5

**Comment by QuiiBz** [comment] 2023-07-20 15:53
Good catch, the fallback locale wasn't flattened. I've fixed it in #73 and released [0.6.3](https://github.com/QuiiBz/next-international/releases/tag/0.6.3) - let me know if it works now!

**Comment by marcohaferkamp** [comment] 2023-07-21 05:26
Works like a charm now. Thanks a lot :)

**Comment by marcohaferkamp** [comment] 2023-07-21 07:55
Sorry, but again a question:
I get typescript errors passing nested translations as fallbackLocale. Do I need to flatten it manually?

**Comment by QuiiBz** [comment] 2023-07-21 08:54
Oh yeah, I forgot about this one, should be fixed in [v0.6.4](https://github.com/QuiiBz/next-international/releases/tag/0.6.4)!
