### ISSUE TITLE
Possibility to wrap translation with tags

### ISSUE THREAD

**Issue by codefln** [QuiiBz/next-international#353] opened 2024-02-12 12:36 UTC
Hi, I may have missed something, but is there an option within a translation file to wrap text with tags?

For example, I have this key:
'auth.confirm':
    "I confirm that I am 18 years old and I've read <link>the terms of service</link>"

And in the component, I want to use
{t('auth.confirm', {link: <Link to="/terms" />})}

Thanks for the replies, sorry I had to create a issue

**Comment by QuiiBz** [comment] 2024-02-16 13:40
Hi, I'm not quite sure to understand your question. Could you expand a bit more your example?

**Comment by codefln** [comment] 2024-02-16 20:13
> Hi, I'm not quite sure to understand your question. Could you expand a bit more your example?

Key:
'auth.confirm': "I confirm that I am 18 years old and I've read the <a>terms of service</a>"

Call:
t('auth.confirm', {a: <a href='/terms' />})

HTML output:
I confirm that I am 18 years old and I've read the <a href='/terms'>terms of service</a>

**Comment by QuiiBz** [comment] 2024-02-17 09:00
Oh thanks, that's kind of a duplicate of https://github.com/QuiiBz/next-international/issues/343 - we'll likely land this feature in the V2: https://github.com/QuiiBz/next-international/issues/359

**Closed by QuiiBz** 2024-02-17 09:00 UTC
Labels: enhancement
