### ISSUE TITLE
Questions about middleware

### ISSUE THREAD

**Issue by iStorry** [QuiiBz/next-international#224] opened 2023-10-05 08:22 UTC
```
import { type NextRequest } from "next/server";
import { getToken } from "next-auth/jwt";
import { createI18nMiddleware } from "next-international/middleware";

const I18nMiddleware = createI18nMiddleware({
  locales: ["en", "ja"],
  defaultLocale: "en",
  urlMappingStrategy: "rewrite",
});

export async function middleware(req: NextRequest) {
  const session = await getToken({ req });

  const { role, profile } = session?.user ?? {};

  if (role === "user" && !profile) {
    const url = req.nextUrl.clone();
    url.pathname = `/user/profile`;
    return NextResponse.rewrite(url);
  }

  return I18nMiddleware(req);
}
```

The NextResponse return 404 page. I think it's because of I18nMiddleware

**Comment by QuiiBz** [comment] 2023-10-05 09:32
Please send a complete reproduction, I can't help with only this middleware file.

**Comment by gustaveWPM** [comment] 2023-10-05 13:24
Well, I think it is not the good way to nest middlewares.

Ping @iStorry

Maybe something like this?

```ts
import { DEFAULT_LANGUAGE, LANGUAGES } from '@/config/i18n';
import { getPathnameWithoutI18nFlag } from '@/lib/i18n';
import { withAuth } from 'next-auth/middleware';
import { createI18nMiddleware } from 'next-international/middleware';
import { NextRequest, NextResponse } from 'next/server';

const PROTECTED_ROUTES = ['/dashboard'];
export const config = {
  matcher: ['/((?!api|static|_next|.*\\..*).*)']
};

const I18nMiddlewareInstance = createI18nMiddleware({
  locales: LANGUAGES,
  defaultLocale: DEFAULT_LANGUAGE,
  urlMappingStrategy: 'rewrite'
});

function i18nMiddleware(request: NextRequest) {
  const i18nResponse: NextResponse = I18nMiddlewareInstance(request);
  return i18nResponse;
}

const authMiddleware = withAuth(
  function onSuccess(req) {
    return i18nMiddleware(req);
  },
  {
    pages: {
      signIn: '/sign-up'
    }
  }
);

export default function middleware(req: NextRequest) {
  const currentRoute = getPathnameWithoutI18nFlag(req.nextUrl.pathname);
  const isProtectedRoute = PROTECTED_ROUTES.find((r) => currentRoute.startsWith(r));

  return isProtectedRoute ? (authMiddleware as any)(req) : i18nMiddleware(req);
}
```

**Comment by iStorry** [comment] 2023-10-05 13:26
Thanks @gustaveWPM  i will look into it tomorrow

**Comment by QuiiBz** [comment] 2023-10-05 15:33
See also https://github.com/QuiiBz/next-international/issues/187 - closing as it isn't directly related to next-international.

**Closed by QuiiBz** 2023-10-05 15:33 UTC
Labels: question, needs reproduction

**Comment by gustaveWPM** [comment] 2023-10-05 17:55
> See also #187 - closing as it isn't directly related to next-international.

Omg, it looks like a better way to solve the problem then mine.
[To be honest, I'm also struggling with something similar, haha!](https://github.com/vercel/next.js/discussions/56326)

Thank you.
