### ISSUE TITLE
[1.1.0-rc.x] Screen flickering on next/prev

### ISSUE THREAD

**Issue by gustaveWPM** [QuiiBz/next-international#208] opened 2023-10-01 10:25 UTC
When I use: `"next-international": "1.1.0-rc.1"`
I get screen flickering when I use the "next" and "previous" buttons of my browser.

https://github.com/QuiiBz/next-international/assets/118654172/bd8c89a8-22e7-4b55-962a-fbefea0286b3

This bug does not occur when I use: `"next-international": "^1.0.1"`

**Comment by QuiiBz** [comment] 2023-10-01 10:28
Please provide a reproduction so I can debug the issue.

**Comment by gustaveWPM** [comment] 2023-10-01 10:29
> Please provide a reproduction so I can debug the issue.

Doesn't this happen with the examples from the repo?

**Comment by QuiiBz** [comment] 2023-10-01 10:32
No, but the example is very minimal and doesn't have any CSS/complex layout. So I'm not sure if it's because of the `Suspense` boundary used by next-international or not.

**Comment by gustaveWPM** [comment] 2023-10-01 10:35
Hmm, wait a minute please.

**Comment by gustaveWPM** [comment] 2023-10-01 10:41
Dunno if it is helpful?
https://github.com/Tirraa/dashboard_rtm/tree/next-international-1.1.0-rc.1-screen-flickering-demo

**Comment by QuiiBz** [comment] 2023-10-01 11:45
You're using `I18nProvider` twice (in `src/app/[locale]/layout.tsx` and `src/components/shared/misc/HtmlElement`). I've kept only the one in `HtmlElement` and moved it inside the body to avoid wrapping both `html` & `body`.

I added a `fallback` prop to `I18nProviderClient` and my assumption was correct: the fallback is triggered when navigating prev/next, and so replaces the whole layout. I'm not sure if this is the intended behaviour of React's `use()` hook.

**Comment by gustaveWPM** [comment] 2023-10-01 11:48
> You're using `I18nProvider` twice (in `src/app/[locale]/layout.tsx` and `src/components/shared/misc/HtmlElement`). I've kept only the one in `HtmlElement` and moved it inside the body to avoid wrapping both `html` & `body`.

Oops! You're right. I messed up when replacing `useCurrentLocale` with `params.locale` in my `<html>` element.

> I added a `fallback` prop to `I18nProviderClient` and my assumption was correct: the fallback is triggered when navigating prev/next, and so replaces the whole layout. I'm not sure if this is the intended behaviour of React's `use()` hook.

:/

**Comment by gustaveWPM** [comment] 2023-10-01 16:16
https://youtu.be/T3m-MZkuadU?t=544
Maybe this?

**Comment by QuiiBz** [comment] 2023-10-01 16:55
I've released this change in `next-international@1.1.0-rc.3`: [`aa19612` (#205)](https://github.com/QuiiBz/next-international/pull/205/commits/aa19612ed04bdde85f4ba9aaf667af9896ea1a2b)

It seems to work but also seems a bit hacky.

**Comment by gustaveWPM** [comment] 2023-10-01 17:02
I tried it, and it _seems_ that it works perfectly. No more screen flickering, still no issue in the staticly generated HTML files.

I don't understand the try/catch block in this commit.

**Comment by gustaveWPM** [comment] 2023-10-01 17:06
Well... If I refresh the page, and then use next/prev buttons, the screens flickering are back. :/

**Comment by QuiiBz** [comment] 2023-10-01 17:24
> I don't understand the try/catch block

React's `cache()` function isn't available on all "environments" (node, dom...), and throws an error if used in one:

![Screenshot 2023-10-01 at 19 21 58](https://github.com/QuiiBz/next-international/assets/43268759/a63e06db-c5d4-49ca-9edf-427f8845713f)

I added a try catch to fallback to loading the locale as before, without using `cache()`.

> the screens flickering are back

Just noticed that, but it seems to only "flicker" (= trigger the `Suspense`' fallback) on the first forward/backward navigation. Going again to the same page doesn't cause a "flicker". This is probably the correct behaviour since the cache is busted because of the refresh.

**Comment by gustaveWPM** [comment] 2023-10-01 18:22
> > I don't understand the try/catch block
> 
> React's `cache()` function isn't available on all "environments" (node, dom...), and throws an error if used in one:
> 
> ![Screenshot 2023-10-01 at 19 21 58](https://user-images.githubusercontent.com/43268759/271843626-a63e06db-c5d4-49ca-9edf-427f8845713f.png)
> 
> I added a try catch to fallback to loading the locale as before, without using `cache()`.
> 
> > the screens flickering are back
> 
> Just noticed that, but it seems to only "flicker" (= trigger the `Suspense`' fallback) on the first forward/backward navigation. Going again to the same page doesn't cause a "flicker". This is probably the correct behaviour since the cache is busted because of the refresh.

This is weird...
The cache should "load" the same informations, so there should be no flicker? :/

**Comment by QuiiBz** [comment] 2023-10-01 18:49
Found the root cause: this `useParams()` seems to invalidate the cache somehow

https://github.com/QuiiBz/next-international/blob/e2821cd04791a56b9276a27eb6b5df33e514e990/packages/next-international/src/app/client/create-use-current-locale.ts#L9

I don't know how to fix this though

**Comment by QuiiBz** [comment] 2023-10-01 19:14
I published `next-international@1.1.0-rc.4` (see https://github.com/QuiiBz/next-international/pull/205/commits/ca9df6525455b2c47c4d658f6eb677de0084b97e) - it adds a required `locale` from to `I18nProviderClient` that is the locale params segment.

**Comment by gustaveWPM** [comment] 2023-10-01 20:32
I always get flashes when I refresh the page, then use the next/prev buttons.
They seem a bit shorter.

**Comment by gustaveWPM** [comment] 2023-10-01 23:17
Also, when I change the locale (using `const changeLocale = useChangeLocale();`, then `changeLocale('it')`) for the first time after loading the page in my web browser, I get a flash. Idk if it was the case before this RC?

**Comment by QuiiBz** [comment] 2023-10-02 06:16
> I still get flashes when I refresh the page, then use the next/prev buttons.

That is expected, similar to the explanation at the bottom. You shouldn't get any "flash" while navigating then going forward/backward during the same session (= not refreshing).

> Does the cache really changes nothing here?

`cache()` is no longer used in the latest rc.

> when I change the locale ... I get a flash

This is a drawback of using `use()`, which doesn't keep the previous value and immediately trigger the nearest `Suspense` boundary. On the other side, `use()` enables Static Rendering for Client Components.

**Comment by gustaveWPM** [comment] 2023-10-02 09:08
> which doesn't keep the previous value

So, why stop using `cache()`?
I don't understand this point. :/

**Comment by QuiiBz** [comment] 2023-10-02 11:51
`cache()` doesn't solve the issue when refreshing the page and going forward/backward. The latest commit essentially does the same thing as when using `cache()`, except that the code is cleaner and makes more sense.

To recap: the last issue is forward/backward navigation immediately after refreshing the page. Normal navigation and Static Rendering are both working as expected. Tbh, this last issue doesn't feel like a huge problem to me. I personally almost never refresh a website, then go forward/backward without navigating to a page.

**Comment by gustaveWPM** [comment] 2023-10-02 13:09
> Tbh, this last issue doesn't feel like a huge problem to me. I personally almost never refresh a website, then go forward/backward without navigating to a page.

I agree.
But I think it might be worth to keep this problem in the issues, in case of a Eureka moment.

**Comment by QuiiBz** [comment] 2023-10-05 09:46
Closing thanks to https://github.com/QuiiBz/next-international/pull/205, will be released during this week officialy.

**Closed by QuiiBz** 2023-10-05 09:46 UTC
Labels: bug
