### ISSUE TITLE
The `Set-Cookie` header is lost after `redirect` in Server Actions

### ISSUE THREAD

**Issue by Yovach** [QuiiBz/next-international#254] opened 2023-10-19 16:06 UTC
**Describe the bug**
The `Set-Cookie` header is lost after using [`redirect`](https://nextjs.org/docs/app/api-reference/functions/redirect) in `Server Actions`.

**To Reproduce**
1. Clone the following repo : https://github.com/Yovach/nextjs-cookies-redirect
2. Start the Next.js dev server (`pnpm dev`)
3. Go to http://localhost:3000/login and submit a random username
4. You're redirected to http://localhost:3000/profile with your username
5. Refresh and your username disappears

**Expected behavior**
The `Set-Cookie` should be shown on the Server Action call.
Go to http://localhost:3000/ok/login and submit an username
You should be redirected to http://localhost:3000/ok/profile and be able to redirect with your username

**About (please complete the following information):**
 - next-international v1.1.3
 - Next.js v13.5.6

**Comment by QuiiBz** [comment] 2023-10-19 18:53
Duplicate of #212

**Closed by QuiiBz** 2023-10-19 18:53 UTC
Labels: bug
