### ISSUE TITLE
Pages with `runtime = 'edge'` don't work

### ISSUE THREAD

**Issue by weeny-V** [QuiiBz/next-international#159] opened 2023-09-07 13:44 UTC
when I'm trying to get translation in the server component with "const t = await getI18n();" I receive this error "Error: Invariant: headers() expects to have requestAsyncStorage, none available."
I think your documentation already has version 1.0.0 but the library is still 0.9.5;

**Comment by QuiiBz** [comment] 2023-09-07 14:49
Hi, the documentation website refers to the v1 version that hasn’t been released yet (#126). Can you send a reproduction link?

**Comment by weeny-V** [comment] 2023-09-07 18:38
Maybe I fix it by myself XD

**Comment by weeny-V** [comment] 2023-09-08 07:52
server i18n methods don't work with "export runtime = 'edge'" but this line is required for building my app

**Comment by QuiiBz** [comment] 2023-09-08 08:45
Unfortunately, this error is caused by a bug (limitation?) in Next.js: https://github.com/vercel/next.js/issues/52176

I've made some changes in #126 that *might* resolve the issue, you can follow the upgrade guide in the PR description by installing `next-international@1.0.0-rc.6`

**Comment by weeny-V** [comment] 2023-09-14 07:13
yeah, sure
First screenshot with all your settings and work correctly:
![image](https://github.com/QuiiBz/next-international/assets/48623554/433b20ed-b1fc-4e3b-bf56-0e52f3e2e524)
The second screenshot with runtime value does not work:
![image](https://github.com/QuiiBz/next-international/assets/48623554/4603bbac-90e5-4be5-a429-3b8a4a1a3a5e)

**Comment by weeny-V** [comment] 2023-09-14 07:14
![image](https://github.com/QuiiBz/next-international/assets/48623554/a1710e56-bea2-4b27-808f-39ed3dce0204)

**Comment by QuiiBz** [comment] 2023-09-15 05:57
I've just tested by adding `export const runtime = 'edge'` to the root page of the example (https://github.com/QuiiBz/next-international/blob/main/examples/next-app/app/%5Blocale%5D/page.tsx), and it seems to work fine. I'll close the issue but feel free to re-open if needed.

**Closed by QuiiBz** 2023-09-15 05:57 UTC
Labels: bug

**Comment by weeny-V** [comment] 2023-12-06 14:06
> Unfortunately having `export const runtime = "edge";` in `src/app/layout.tsx` file still does not work for we with `"next-international": "^1.1.4"` & `"next": "14.0.3"`
> 
> ```
> Error:Failed to load chunk chunks/src_locales_en_ts_a5d485._.js from module [project]/src/locales/en.ts [edge_rsc] (ecmascript, loader): Error: chunk loading is not supported
> ```
> 
> works only if I remove `export const runtime = "edge";` from `src/app/layout.tsx` file.

It's also not working for me if I am using it on localhost but then I posted it to one of the domains in my case it was Cloudflare it works correctly. So when I work on localhost I just comment this line with "runtime = edge" and when I push it to remote repository I just uncomment this line
