### ISSUE TITLE
Use of I18nProviderClient in jest tests

### ISSUE THREAD

**Issue by murphcfa** [QuiiBz/next-international#348] opened 2024-02-08 21:00 UTC
**Describe the bug**

Error thrown when using I18nProviderClient in a jest test

**To Reproduce**
1. Create client component that is wrapped in the I18nProviderClient
2. Create jest test for component and wrap component in I18nProviderClient within the test
4. See error TypeError: (0 , import_react.use) is not a function

**Expected behavior**
Test would pass

**Screenshots**

![Screenshot 2024-02-08 at 3 58 07 PM](https://github.com/QuiiBz/next-international/assets/153104339/312d86e1-d6fb-4749-a878-0e36476d51f8)

![Screenshot 2024-02-08 at 3 57 58 PM](https://github.com/QuiiBz/next-international/assets/153104339/43da66aa-bb0a-4fa5-b256-7c4e39ef0c3e)

**About (please complete the following information):**
 - next-international version 1.2.3
 - Next.js version 14.0.4
 - React version 18

**Additional context**

I am trying to write a jest test for a component that leverages the I18nProviderClient but am seeing some errors. I imagine this is due to something I have configured incorrectly, however, due to no examples being provided for unit testing I am unsure how you would properly set this up. Has anyone else experienced this?

**Comment by QuiiBz** [comment] 2024-02-09 14:20
Closing as duplicate of https://github.com/QuiiBz/next-international/issues/178 - I believe we haven't found yet a proper solution to test Next.js App Router with the new React features.

**Closed by QuiiBz** 2024-02-09 14:20 UTC
Labels: bug
